[workspace]
resolver = "3"

[package]
name = "invoker"
version = "0.2.0"
edition = "2024"

[dependencies]
rand = "*"

log = "*"
env_logger = "*"
colored = "*"

tokio = "*"

ratchet_rs = { version = "*", features = ["deflate", "split"] }
bytes = "*"

futures = "*"

http = "*"
anyhow = "*"

serde = { version = "*", features = ["derive"] }
serde_yml = "*"

uuid = { version = "*", features = ["v4"] }
envy = "*"

toaster_lib_rs = {git = "https://github.com/summer-54/toaster_lib_rs.git"}

tar_archive_rs = {git = "https://github.com/summer-54/tar_archive_rs.git"}

configo = {git = "https://github.com/summer-54/configo.git"}


nix = {version = "*", features = ["user"]}

async-trait = {version = "*"}

bytesize = {version = "*"}
lru = {version = "*"}

tonic = "*"
tokio-stream = "*"

[features]
default = []
mock = []
